### ISSUE TITLE
synonyms.txt may contain sensitive words

### ISSUE THREAD

**Issue by lapis-zero09** [WorksApplications/SudachiDict#15]
I found "公僕" in SudachiDict/src/main/text/synonyms.txt.
If the inclusion is as intended, close this issue.

In some cases,  "公僕" can be perceived as discriminatory terms.
You may want to delete.

**Comment by kazuma-t** [comment]
First of all, we do not consider "公僕" a discriminatory term.
The following is our treatment of discriminatory terms.

synonyms.txt describes the synonyms between words in the system dictionary of Sudachi. Every word in it can be included in synonyms.txt.
The system dictionary contains such words because tokenizer needs to be able to handle even discriminatory terms.

It is a problem if synonyms.txt is used for generating purposes. In that case, please refer to the category information and remove  the word classified as "不快".
